---
title: "R Notebook"
output: html_notebook
---

```{r}
library(rJava)

# this works with OSP source code but pointing to the bin folder
ospClasses <- "C:/Users/msfz751/Desktop/git.public/java-opensourcephysics/2015PortableWS/osp/bin"
ospClasses1 <- "C:/Users/msfz751/Desktop/git.public/java-opensourcephysics/2015PortableWS/osp_csm/bin"
.jinit()          # initialize Java-VM
.jaddClassPath(ospClasses)
.jaddClassPath(ospClasses1)
.jclassPath()
```


```{r}
projectile <- J("org.opensourcephysics.sip.ch03.Projectile")
.jmethods(projectile)
```

```{r}
.jfields(projectile)
```

```{r}
prj <- .jnew(projectile)
```

```{r}
state <- rate <- .jcall(prj, "[D", "getState")
state
rate
```



```{r}
new_rate <- .jcall(prj, "V", "getRate", as.double(state), as.double(rate))
new_rate
```

```{r}
state_set <- .jcall(prj, "V", "setState", as.double(0), as.double(1), as.double(2), as.double(3))
state_set
```

```{r}
.jcall(prj, "[D", "getState")
```



```{r}
.projectileApp <- J("org.opensourcephysics.sip.ch03.ProjectileApp")
```

```{r}
projectileApp <- .jnew(.projectileApp)

```

```{r}
.jcall(projectileApp, "V", "initialize")
```



```{r}
.jcall(projectileApp, "V", "reset")
```


```{r}
.jcall(projectileApp, "V", "doStep")
```


```{r}
simulationControl <- J("org.opensourcephysics.controls.SimulationControl")
simulationControl$createApp(projectileApp)
```






```{r}
projectileApp$initialize()
```

```{r}
projectileApp$doStep()
```

```{r}
.jcall(projectileApp, "V", "startProjectile")
```

```{r}
.jcall(.projectileApp, "V", "startProjectile")
```



```{r}
projectileApp$stopSimulation()
```







```{r}
.jmethods(projectileApp)
```


```{r}
.jmethods(simulationControl)
```

